[package]
name        = "holo-run-scripts"
version     = "1.3"
release     = 1
description = "Holo plugin for running custom provisioning scripts"
author      = "Stefan Majewsky <holo-packaging@posteo.de>"
